INSERT INTO CAMPANHA (ID_CAMPANHA, NOME_CAMPANHA, ID_TIME_CORACAO, DATA_INICIO, DATA_FIM) VALUES (1, 'Campanha de Inverno', 1, TO_DATE('2017-06-01', 'YYYY-MM-DD'), TO_DATE('2017-10-03', 'YYYY-MM-DD'));
INSERT INTO CAMPANHA (ID_CAMPANHA, NOME_CAMPANHA, ID_TIME_CORACAO, DATA_INICIO, DATA_FIM) VALUES (2, 'Campanha de Verao', 2, TO_DATE('2017-06-01', 'YYYY-MM-DD'), TO_DATE('2017-10-02', 'YYYY-MM-DD'));

INSERT INTO TORCEDORCAMPANHA (ID_TORCEDORCAMPANHA, EMAIL, TIME_CORACAO, ID_CAMPANHA) VALUES (1, 'thiago@hotmail.com', 'Portuguesa', 1);
INSERT INTO TORCEDORCAMPANHA (ID_TORCEDORCAMPANHA, EMAIL, TIME_CORACAO, ID_CAMPANHA) VALUES (2, 'marcos@hotmail.com', 'Guarani', 2);